#!/bin/bash
## Description: Create VSCode configuration files for debugging DDEV
## Usage: vscode
## Example: ddev vscode
# Verifies if .vscode exists at the project root
if [ -d ".vscode" ]; then
    echo ".vscode directory already exists. No files were created."
    exit 0
else
    mkdir -p .vscode
    echo "Created .vscode directory."

    cat > .vscode/tasks.json << 'JSON'
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "DDEV: Enable Xdebug",
            "type": "shell",
            "command": "ddev xdebug on"
        },
        {
            "label": "DDEV: Disable Xdebug",
            "type": "shell",
            "command": "ddev xdebug off"
        }
    ]
}
JSON
    echo "Created tasks.json in .vscode directory."

    cat > .vscode/launch.json << 'CONFIG'
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "hostname": "0.0.0.0",
            "port": 9003,
            "pathMappings": {
                "/var/www/html": "\${workspaceFolder}"
            },
            "preLaunchTask": "DDEV: Enable Xdebug",
            "postDebugTask": "DDEV: Disable Xdebug"
        }
    ]
}
CONFIG
    echo "Created launch.json in .vscode directory."
fi
